name: MetrixHD

on:
  push:
    branches: [ 7.1 ]
  pull_request:
    branches: [ 7.1 ]

jobs:
  build:
    name: Build MetrixHD
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt-get install automake
          sudo apt-get install build-essential
          sudo apt-get install gettext

      - uses: actions/checkout@v2
        with:
          ref: '7.1'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Build, python 3.10
        run: |
          python -m compileall .

      - uses: actions/checkout@v2
        with:
          ref: '7.1'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Build, python 3.11
        run: |
          python -m compileall .
